controller_manager:
  ros__parameters:
    update_rate: 100
    mecanum_cont:
      type: mecanum_drive_controller/MecanumDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_cont:
  ros__parameters:
    front_left_wheel_name: front_left_joint
    front_right_wheel_name: front_right_joint
    rear_left_wheel_name: rear_left_joint
    rear_right_wheel_name: rear_right_joint
    
    # Geometry (measure your digital twin!)
    wheel_separation_x: 0.30 
    wheel_separation_y: 0.36
    wheel_radius: 0.05
    
    # Frames
    base_frame_id: base_link
    odom_frame_id: odom
    
    # Kinematics
    use_stamped_vel: false